In [1]:
import pandas as pd
import numpy as np

In [2]:
ds = pd.read_csv('Dataset/NB_computer.csv')
ds

Age  income student Credit rating buys computer (Y/N)
0         youth    high      no          fair                  no
1         youth    high      no     excellent                  no
2   middle aged    high      no          fair                 yes
3        senior  medium      no          fair                 yes
4        senior     low     yes          fair                 yes
5        senior     low     yes     excellent                  no
6   middle aged     low     yes     excellent                 yes
7         youth  medium      no          fair                  no
8         youth     low     yes          fair                 yes
9        senior  medium     yes          fair                 yes
10        youth  medium     yes     excellent                 yes
11  middle aged  medium      no     excellent                 yes
12  middle aged    high     yes          fair                 yes
13       senior  medium      no     excellent                  no

In [3]:
x = ds.iloc[:,:-1].values
x

array([['youth', 'high', 'no', 'fair'],
       ['youth', 'high', 'no', 'excellent'],
       ['middle aged', 'high', 'no', 'fair'],
       ['senior', 'medium', 'no', 'fair'],
       ['senior', 'low', 'yes', 'fair'],
       ['senior', 'low', 'yes', 'excellent'],
       ['middle aged', 'low', 'yes', 'excellent'],
       ['youth', 'medium', 'no', 'fair'],
       ['youth', 'low', 'yes', 'fair'],
       ['senior', 'medium', 'yes', 'fair'],
       ['youth', 'medium', 'yes', 'excellent'],
       ['middle aged', 'medium', 'no', 'excellent'],
       ['middle aged', 'high', 'yes', 'fair'],
       ['senior', 'medium', 'no', 'excellent']], dtype=object)

In [4]:
y = ds.iloc[:,-1].values
y

array(['no', 'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])
x[:, 2] = labelencoder_X.fit_transform(x[:, 2])
x[:, 3] = labelencoder_X.fit_transform(x[:, 3])
print(x)

[[2 0 0 1]
 [2 0 0 0]
 [0 0 0 1]
 [1 2 0 1]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 1 0]
 [2 2 0 1]
 [2 1 1 1]
 [1 2 1 1]
 [2 2 1 0]
 [0 2 0 0]
 [0 0 1 1]
 [1 2 0 0]]


In [6]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier = classifier.fit(x,y)

In [8]:
prediction = classifier.predict([[2,2,1,1]])
prediction

array(['yes'], dtype='<U3')