In [12]:
import pandas as pd
import numpy as np

In [13]:
ds = pd.read_csv('Dataset/play.csv')
ds

outlook temperature humidity  windy Play(Y/N)
0   Sunny         Hot     High  False        No
1   Sunny         Hot     High   True        No
2   Rainy        Mild     High  False       Yes
3   Rainy        Cool   Normal  False       Yes
4   Rainy        Cool   Normal   True        No
5   Sunny        Mild     High  False        No
6   Sunny        Cool   Normal  False       Yes
7   Rainy        Mild   Normal  False       Yes
8   Sunny        Mild   Normal   True       Yes
9   Rainy        Mild     High   True        No

In [14]:
x = ds.iloc[:,:-1].values
x

array([['Sunny', 'Hot', 'High', False],
       ['Sunny', 'Hot', 'High', True],
       ['Rainy', 'Mild', 'High', False],
       ['Rainy', 'Cool', 'Normal', False],
       ['Rainy', 'Cool', 'Normal', True],
       ['Sunny', 'Mild', 'High', False],
       ['Sunny', 'Cool', 'Normal', False],
       ['Rainy', 'Mild', 'Normal', False],
       ['Sunny', 'Mild', 'Normal', True],
       ['Rainy', 'Mild', 'High', True]], dtype=object)

In [15]:
y = ds.iloc[:,-1].values
y

array(['No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'No'],
      dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
x[:, 0] = labelencoder_X.fit_transform(x[:, 0])
x[:, 1] = labelencoder_X.fit_transform(x[:, 1])
x[:, 2] = labelencoder_X.fit_transform(x[:, 2])
x[:, 3] = labelencoder_X.fit_transform(x[:, 3])
print(x)

[[1 1 0 0]
 [1 1 0 1]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 1 1]
 [1 2 0 0]
 [1 0 1 0]
 [0 2 1 0]
 [1 2 1 1]
 [0 2 0 1]]


In [17]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier = classifier.fit(x,y)

In [18]:
prediction = classifier.predict([[1,0,0,0]])
prediction

array(['No'], dtype='<U3')