In [3]:
import pandas as pd
import numpy as np

In [4]:
ds = pd.read_csv('Dataset/buy_car.csv')
ds

Montly Salary  age  Y/N
0             2386   18    0
1             2486   19    0
2             2586   20    0
3             2686   20    0
4             2756   20    0
..             ...  ...  ...
395          12557   60    1
396          14270   60    1
397          10262   60    1
398           7782   60    0
399          11186   60    1

[400 rows x 3 columns]

In [5]:
x = ds.iloc[:,:-1].values
x

array([[ 2386,    18],
       [ 2486,    19],
       [ 2586,    20],
       [ 2686,    20],
       [ 2756,    20],
       [ 2896,    20],
       [ 2500,    20],
       [ 2400,    20],
       [ 2300,    20],
       [ 2679,    20],
       [ 2156,    20],
       [ 2641,    20],
       [ 2696,    21],
       [ 2519,    21],
       [ 2631,    21],
       [ 2596,    21],
       [ 2563,    21],
       [ 2612,    21],
       [ 2505,    21],
       [ 2690,    21],
       [ 2662,    21],
       [ 2748,    22],
       [ 2600,    22],
       [ 2638,    22],
       [ 2676,    22],
       [ 2604,    22],
       [ 2670,    22],
       [ 2600,    22],
       [ 2718,    22],
       [ 2720,    23],
       [ 2740,    23],
       [ 2716,    23],
       [ 2700,    23],
       [ 2761,    23],
       [ 2779,    24],
       [ 2759,    24],
       [ 2755,    24],
       [ 2758,    24],
       [ 2799,    24],
       [ 2732,    24],
       [ 2766,    24],
       [ 2718,    24],
       [ 2763,    24],
       [ 29

In [6]:
y = ds.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, train_size=0.2, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

x_train, x_test

(array([[-0.69488626, -0.71387762],
        [ 0.4109222 ,  1.25839689],
        [ 0.64088293,  1.60140116],
        [-0.38161546,  0.4866373 ],
        [ 2.06682667,  1.00114369],
        [-0.11920437, -0.0278691 ],
        [-0.69925458, -1.05688189],
        [-0.67117253, -0.79962869],
        [ 1.76416465,  1.08689476],
        [ 2.0740032 ,  1.34414796],
        [-0.85776211, -0.97113082],
        [-0.76197114, -1.05688189],
        [-0.08893817,  0.57238837],
        [-0.67304467, -0.79962869],
        [-0.16444766,  0.7438905 ],
        [-0.88740426, -1.39988615],
        [ 0.5429078 ,  0.91539263],
        [-0.07552119,  0.4866373 ],
        [ 2.70335299,  1.25839689],
        [-0.92515901, -1.48563722],
        [-0.72546448, -0.88537976],
        [ 0.60406425,  1.34414796],
        [-0.18192094,  0.57238837],
        [ 2.88526222,  1.17264583],
        [-0.91392619, -1.48563722],
        [-0.89021247, -1.39988615],
        [ 1.49208086,  1.17264583],
        [-0.6184407 , -0.713

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [10]:
y_pred = classifier.predict(x_test)
y_pred, y_test

(array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[149,   9],
       [  7, 155]])

In [13]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.95

In [12]:
classifier.predict(sc_x.transform([[15000,21]]))

array([1])