In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
pricedf = pd.read_csv('Dataset/MLR_mix.csv')
pricedf

S&P department (spend)  Admin department(spend)  \
0                   101184                    70674   
1                    70132                    52030   
2                   149539                    98535   
3                    75821                    53649   
4                    97730                    68667   
5                    84544                    60923   
6                   117490                    85379   
7                   119913                    86499   
8                   145244                    95108   
9                   147217                    95598   
10                   81746                    56815   
11                  107967                    74058   
12                   74692                    52493   
13                   72228                    52210   
14                   96292                    68521   
15                  124506                    86995   
16                  113543                    82796   
17                  142585                    94589   
18                  118057                    86227   
19                   86260                    63082   
20                   63601                    51026   
21                  113200                    76388   
22                  141331                    93725   
23                   79667                    54864   
24                  112208                    75407   
25                   82622                    59754   
26                  127721                    88888   
27                  117901                    85532   
28                  147364                    96275   
29                  110661                    75404   
30                  107360                    73604   
31                   87194                    63403   
32                   75381                    52575   
33                  113427                    78653   
34                  103004                    71720   
35                  109249                    74209   
36                  134157                    92647   
37                  116481                    83866   
38                   85908                    61800   
39                  131088                    89489   
40                   81818                    57716   
41                   87227                    67434   
42                  103666                    72280   
43                  134089                    91457   
44                  100846                    69194   
45                   63540                    50907   
46                  114384                    83388   
47                   53199                    50191   
48                  131777                    89570   
49                  110643                    74362   

    Operation department(spend) state  Profit  
0                         97009     A  259480  
1                         63587     B  137019  
2                        199994     A  495552  
3                         66500     B  165057  
4                         91754     B  247841  
5                         81618     B  219307  
6                        146277     A  391954  
7                        150579     B  402015  
8                        189066     B  458358  
9                        190309     A  463330  
10                        72351     B  188824  
11                       106215     A  305250  
12                        64267     A  155036  
13                        63719     A  151200  
14                        90007     B  244265  
15                       153382     A  404608  
16                       122345     B  383129  
17                       184603     A  455845  
18                       146948     A  397294  
19                        85320     A  223401  
20                        59932     A  134898  
21                       115984     A  357903  
22                       171453     B  438294  
23                        69102     A  173898 

In [4]:
pricedf.shape

(50, 5)

In [43]:
x = pricedf.iloc[:,:-1].values
print(x)

[[101184 70674 97009 'A']
 [70132 52030 63587 'B']
 [149539 98535 199994 'A']
 [75821 53649 66500 'B']
 [97730 68667 91754 'B']
 [84544 60923 81618 'B']
 [117490 85379 146277 'A']
 [119913 86499 150579 'B']
 [145244 95108 189066 'B']
 [147217 95598 190309 'A']
 [81746 56815 72351 'B']
 [107967 74058 106215 'A']
 [74692 52493 64267 'A']
 [72228 52210 63719 'A']
 [96292 68521 90007 'B']
 [124506 86995 153382 'A']
 [113543 82796 122345 'B']
 [142585 94589 184603 'A']
 [118057 86227 146948 'A']
 [86260 63082 85320 'A']
 [63601 51026 59932 'A']
 [113200 76388 115984 'A']
 [141331 93725 171453 'B']
 [79667 54864 69102 'A']
 [112208 75407 115316 'B']
 [82622 59754 72987 'A']
 [127721 88888 153477 'B']
 [117901 85532 146822 'B']
 [147364 96275 191812 'B']
 [110661 75404 114864 'A']
 [107360 73604 100773 'B']
 [87194 63403 87468 'B']
 [75381 52575 66116 'A']
 [113427 78653 119763 'A']
 [103004 71720 100065 'B']
 [109249 74209 109578 'B']
 [134157 92647 167690 'B']
 [116481 83866 141719 'A']
 [8

In [44]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_x = LabelEncoder()
x[:, 3] = labelencoder_x.fit_transform(x[:, 3])
ct = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)
x = x[:,1:]
print(x)


[[0.0 101184 70674 97009]
 [1.0 70132 52030 63587]
 [0.0 149539 98535 199994]
 [1.0 75821 53649 66500]
 [1.0 97730 68667 91754]
 [1.0 84544 60923 81618]
 [0.0 117490 85379 146277]
 [1.0 119913 86499 150579]
 [1.0 145244 95108 189066]
 [0.0 147217 95598 190309]
 [1.0 81746 56815 72351]
 [0.0 107967 74058 106215]
 [0.0 74692 52493 64267]
 [0.0 72228 52210 63719]
 [1.0 96292 68521 90007]
 [0.0 124506 86995 153382]
 [1.0 113543 82796 122345]
 [0.0 142585 94589 184603]
 [0.0 118057 86227 146948]
 [0.0 86260 63082 85320]
 [0.0 63601 51026 59932]
 [0.0 113200 76388 115984]
 [1.0 141331 93725 171453]
 [0.0 79667 54864 69102]
 [1.0 112208 75407 115316]
 [0.0 82622 59754 72987]
 [1.0 127721 88888 153477]
 [1.0 117901 85532 146822]
 [1.0 147364 96275 191812]
 [0.0 110661 75404 114864]
 [1.0 107360 73604 100773]
 [1.0 87194 63403 87468]
 [0.0 75381 52575 66116]
 [0.0 113427 78653 119763]
 [1.0 103004 71720 100065]
 [1.0 109249 74209 109578]
 [1.0 134157 92647 167690]
 [0.0 116481 83866 141719]
 [1

In [30]:
y = pricedf.iloc[:,-1].values
print(y)

[259480 137019 495552 165057 247841 219307 391954 402015 458358 463330
 188824 305250 155036 151200 244265 404608 383129 455845 397294 223401
 134898 357903 438294 173898 332482 210403 413243 397289 466013 326695
 300970 229567 159141 363228 271059 317476 432552 391295 222793 416910
 193164 241206 282378 426668 251350 115258 389887 110874 425351 324743]


In [31]:
pricedf.corr()

S&P department (spend)  Admin department(spend)  \
S&P department (spend)                     1.000000                 0.984560   
Admin department(spend)                    0.984560                 1.000000   
Operation department(spend)                0.976437                 0.980723   
Profit                                     0.982576                 0.993823   

                             Operation department(spend)    Profit  
S&P department (spend)                          0.976437  0.982576  
Admin department(spend)                         0.980723  0.993823  
Operation department(spend)                     1.000000  0.975566  
Profit                                          0.975566  1.000000

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [34]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train, y_train)

print('Coefficients, beta:', regressor.coef_)
print('Contant, alpha:', regressor.predict([[0,0,0,0]]))

Coefficients, beta: [-7.64437381e+03  6.21135973e-01  6.94950794e+00 -1.91570893e-01]
Contant, alpha: [-247075.19282106]


In [35]:
y_pred = regressor.predict(x_test)
print(y_pred) # comparison predict
print(y_test) # and actual

[469131.79514153 314305.95098855 177031.76224272 251333.22466428
 492265.59457446 384791.47672058 212333.02403266 223303.09210661
 451563.42840049 265608.51763769]
[466013 305250 188824 241206 495552 397289 222793 229567 438294 247841]


In [14]:
corr = np.corrcoef(y_pred, y_test)
print(corr) # check correlation between predicted and actual.

[[1.         0.99542528]
 [0.99542528 1.        ]]


In [15]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)
print(MSE)

114075328.33234176
